// <auto-generated />
using System;
using System.Collections.Generic;
using System.Text.Json;
using MediTrail.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediTrail.Api.Data.Migrations
{
    [DbContext(typeof(MediTrailDbContext))]
    [Migration("20260817054439_AddChatMessages")]
    partial class AddChatMessages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DetectedBy")
                        .HasColumnType("text")
                        .HasColumnName("detected_by");

                    b.PrimitiveCollection<List<Guid>>("EvidenceDocumentIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("evidence_document_ids");

                    b.Property<string>("ExplanationEn")
                        .HasColumnType("text")
                        .HasColumnName("explanation_en");

                    b.Property<string>("ExplanationTa")
                        .HasColumnType("text")
                        .HasColumnName("explanation_ta");

                    b.PrimitiveCollection<List<string>>("InvolvedGenerics")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("involved_generics");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<bool>("RequiresProfessionalConsult")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_professional_consult");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("SuggestedActionEn")
                        .HasColumnType("text")
                        .HasColumnName("suggested_action_en");

                    b.Property<string>("SuggestedActionTa")
                        .HasColumnType("text")
                        .HasColumnName("suggested_action_ta");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)")
                        .HasColumnName("type");

                    b.Property<string>("VerificationExcerpt")
                        .HasColumnType("text")
                        .HasColumnName("verification_excerpt");

                    b.Property<string>("VerificationSource")
                        .HasColumnType("text")
                        .HasColumnName("verification_source");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("verification_status");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("PatientId", "Severity")
                        .HasDatabaseName("ix_alerts_patient_id_severity");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Allergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsDocumentWarning")
                        .HasColumnType("boolean")
                        .HasColumnName("is_document_warning");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Reaction")
                        .HasColumnType("text")
                        .HasColumnName("reaction");

                    b.PrimitiveCollection<List<string>>("RelatesTo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("relates_to");

                    b.Property<string>("Severity")
                        .HasColumnType("text")
                        .HasColumnName("severity");

                    b.Property<string>("SourceText")
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<string>("Substance")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("substance");

                    b.Property<string>("SubstanceGeneric")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("substance_generic");

                    b.HasKey("Id")
                        .HasName("pk_allergies");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_allergies_document_id");

                    b.HasIndex("PatientId", "IsDocumentWarning")
                        .HasDatabaseName("ix_allergies_patient_id_is_document_warning");

                    b.ToTable("allergies", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("answer_en");

                    b.Property<string>("AnswerTa")
                        .HasColumnType("text")
                        .HasColumnName("answer_ta");

                    b.Property<string>("AnswerTanglish")
                        .HasColumnType("text")
                        .HasColumnName("answer_tanglish");

                    b.Property<string>("AskedLanguage")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("asked_language");

                    b.PrimitiveCollection<List<Guid>>("Citations")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("citations");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<bool>("ConsultProfessional")
                        .HasColumnType("boolean")
                        .HasColumnName("consult_professional");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("FoundInDocuments")
                        .HasColumnType("boolean")
                        .HasColumnName("found_in_documents");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("question");

                    b.Property<bool>("SafetyRefusal")
                        .HasColumnType("boolean")
                        .HasColumnName("safety_refusal");

                    b.HasKey("Id")
                        .HasName("pk_chat_messages");

                    b.HasIndex("PatientId", "CreatedAt")
                        .HasDatabaseName("ix_chat_messages_patient_id_created_at");

                    b.ToTable("chat_messages", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Diagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SourceText")
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<string>("Text")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_diagnoses");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_diagnoses_document_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_diagnoses_patient_id");

                    b.ToTable("diagnoses", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer")
                        .HasColumnName("completion_tokens");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("DocumentDate")
                        .HasColumnType("date")
                        .HasColumnName("document_date");

                    b.Property<string>("DocumentType")
                        .HasColumnType("text")
                        .HasColumnName("document_type");

                    b.Property<DateTimeOffset?>("ExtractedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extracted_at");

                    b.Property<int?>("ExtractionLatencyMs")
                        .HasColumnType("integer")
                        .HasColumnName("extraction_latency_ms");

                    b.Property<string>("ExtractionModel")
                        .HasColumnType("text")
                        .HasColumnName("extraction_model");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("LegibilityNotes")
                        .HasColumnType("text")
                        .HasColumnName("legibility_notes");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_file_name");

                    b.Property<int?>("OverallConfidence")
                        .HasColumnType("integer")
                        .HasColumnName("overall_confidence");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer")
                        .HasColumnName("prompt_tokens");

                    b.Property<string>("ProviderFacility")
                        .HasColumnType("text")
                        .HasColumnName("provider_facility");

                    b.Property<string>("ProviderName")
                        .HasColumnType("text")
                        .HasColumnName("provider_name");

                    b.Property<JsonDocument>("RawExtractionJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_extraction_json");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)")
                        .HasColumnName("storage_path");

                    b.Property<string>("VisitLabel")
                        .HasColumnType("text")
                        .HasColumnName("visit_label");

                    b.HasKey("Id")
                        .HasName("pk_documents");

                    b.HasIndex("Sha256")
                        .HasDatabaseName("ix_documents_sha256");

                    b.HasIndex("PatientId", "DocumentDate")
                        .HasDatabaseName("ix_documents_patient_id_document_date");

                    b.HasIndex("PatientId", "Status")
                        .HasDatabaseName("ix_documents_patient_id_status");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.LabResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<bool>("IsOutOfRange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_out_of_range");

                    b.Property<decimal?>("NormalMax")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("normal_max");

                    b.Property<decimal?>("NormalMin")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("normal_min");

                    b.Property<string>("NormalRangeText")
                        .HasColumnType("text")
                        .HasColumnName("normal_range_text");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("SourceText")
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<DateOnly?>("TestDate")
                        .HasColumnType("date")
                        .HasColumnName("test_date");

                    b.Property<string>("TestName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_name");

                    b.Property<string>("TestNameStandard")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("test_name_standard");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<decimal?>("ValueNumeric")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("value_numeric");

                    b.Property<string>("ValueText")
                        .HasColumnType("text")
                        .HasColumnName("value_text");

                    b.HasKey("Id")
                        .HasName("pk_lab_results");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_lab_results_document_id");

                    b.HasIndex("PatientId", "TestNameStandard", "TestDate")
                        .HasDatabaseName("ix_lab_results_patient_id_test_name_standard_test_date");

                    b.ToTable("lab_results", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("brand_name");

                    b.Property<int?>("Confidence")
                        .HasColumnType("integer")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("Dose")
                        .HasColumnType("text")
                        .HasColumnName("dose");

                    b.Property<int?>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Frequency")
                        .HasColumnType("text")
                        .HasColumnName("frequency");

                    b.Property<decimal?>("FrequencyPerDay")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("frequency_per_day");

                    b.Property<string>("GenericName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("generic_name");

                    b.Property<string>("Instructions")
                        .HasColumnType("text")
                        .HasColumnName("instructions");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Route")
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<string>("SourceText")
                        .HasColumnType("text")
                        .HasColumnName("source_text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("StrengthUnit")
                        .HasColumnType("text")
                        .HasColumnName("strength_unit");

                    b.Property<decimal?>("StrengthValue")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("strength_value");

                    b.HasKey("Id")
                        .HasName("pk_medications");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("ix_medications_document_id");

                    b.HasIndex("PatientId", "GenericName")
                        .HasDatabaseName("ix_medications_patient_id_generic_name");

                    b.ToTable("medications", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("text")
                        .HasColumnName("status_message");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_patients");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_patients_created_at");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Alert", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Patient", "Patient")
                        .WithMany("Alerts")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Allergy", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Document", "Document")
                        .WithMany("Allergies")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_allergies_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.ChatMessage", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Patient", "Patient")
                        .WithMany("ChatMessages")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_messages_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Diagnosis", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Document", "Document")
                        .WithMany("Diagnoses")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_diagnoses_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Document", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Patient", "Patient")
                        .WithMany("Documents")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documents_patients_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.LabResult", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Document", "Document")
                        .WithMany("LabResults")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lab_results_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Medication", b =>
                {
                    b.HasOne("MediTrail.Api.Data.Entities.Document", "Document")
                        .WithMany("Medications")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medications_documents_document_id");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Document", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Diagnoses");

                    b.Navigation("LabResults");

                    b.Navigation("Medications");
                });

            modelBuilder.Entity("MediTrail.Api.Data.Entities.Patient", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("ChatMessages");

                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
